added Systems Manager access

diff --git a/.github/workflows/terraform_deploy.yml b/.github/workflows/terraform_deploy.yml
--- a/.github/workflows/terraform_deploy.yml
+++ b/.github/workflows/terraform_deploy.yml
@@ -151,23 +151,21 @@ jobs:
                     
             - name: Get Terraform outputs
               run: |
-                echo "K3S_SERVER_ID=$(terraform output -raw k3s_server_id || echo '')" >> $GITHUB_ENV
-                echo "BASTION_PUBLIC_IP=$(terraform output -raw bastion_public_ip || echo '')" >> $GITHUB_ENV
+                  echo "K3S_SERVER_ID=$(terraform output -raw k3s_server_id || echo '')" >> $GITHUB_ENV
+                  echo "BASTION_PUBLIC_IP=$(terraform output -raw bastion_public_ip || echo '')" >> $GITHUB_ENV
                                         
 
             - name: Post-provisioning configuration
               run: |
-                if [ -z "$K3S_SERVER_ID" ]; then
-                  echo "K3s server ID not found in Terraform output. Skipping post-provisioning steps."
-                else
-                  if [ -z "$BASTION_PUBLIC_IP" ]; then
-                    echo "Attempting to connect directly to K3s server..."
-                    aws ssm start-session --target $K3S_SERVER_ID --document-name AWS-StartInteractiveCommand --parameters command="kubectl get nodes"
+                  if [ -z "$K3S_SERVER_ID" ]; then
+                    echo "K3s server ID not found in Terraform output. Skipping post-provisioning steps."
                   else
-                    echo "Bastion public IP found, but direct connection to K3s server will be attempted..."
-                    aws ssm start-session --target $K3S_SERVER_ID --document-name AWS-StartInteractiveCommand --parameters command="kubectl get nodes"
+                    echo "Attempting to connect to K3s server..."
+                    aws ssm start-session \
+                      --target $K3S_SERVER_ID \
+                      --document-name AWS-StartInteractiveCommand \
+                      --parameters command="kubectl get nodes -o name | cut -d'/' -f2 | xargs -I {} kubectl label node {} node-role.kubernetes.io/worker=worker --overwrite"
                   fi
-                fi
               env:
                 AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
                 AWS_REGION: us-east-1
